plugins {
  alias(libs.plugins.android.library)
  alias(libs.plugins.sqldelight)
}

android {
  namespace = "com.example.sqldelight"

  compileSdk = libs.versions.compileSdk.get() as int

  lint {
    textReport true
  }
}

def debugOnly = providers.gradleProperty("debugOnly").getOrElse("false").toBoolean()

androidComponents {
  beforeVariants(selector().withBuildType("release")) {
    enable = !debugOnly
  }
}

sqldelight {
  databases {
    TestDb {
      packageName = "com.example.sqldelight"
    }
  }
}
