name: Publish a release

on:
  push:
    branches:
      - main
    tags:
      - '*'

concurrency:
  group: "release-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  publish_archives:
    runs-on: macos-latest
    if: github.repository == 'sqldelight/sqldelight'
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.ci-java-version
      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-cleanup: always

      # Build all artifacts with full parallelism.
      - run: ./gradlew publishToMavenLocal
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SECRET_KEY }}

      # Publish to Maven Central without parallelism to try and avoid rate limiting.
      - run: ./gradlew publishToMavenCentral --no-parallel
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SECRET_KEY }}

  publish_plugin:
    runs-on: ubuntu-latest
    if: github.repository == 'sqldelight/sqldelight'
    permissions:
      contents: read
    needs: publish_archives
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      # https://github.com/gradle/gradle-build-action/issues/561
      - name: Create Gradle files
        run: |
          cd ~
          mkdir -p .gradle/ && touch .gradle/gradle.properties
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        id: setup-java
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.ci-java-version
      - name: Setup Gradle Java installations paths
        run: |
          cd ~/.gradle
          echo "org.gradle.java.installations.paths=${{ steps.setup-java.outputs.path }}" >> gradle.properties
      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-cleanup: always

      - name: Publish the plugin artifacts
        env:
          ORG_GRADLE_PROJECT_SQLDELIGHT_BUGSNAG_KEY: ${{ secrets.BUGSNAG_KEY }}
          ORG_GRADLE_PROJECT_intellijPublishToken: ${{ secrets.JETBRAINS_MARKETPLACE_TOKEN }}
        run: ./gradlew publishPlugin --no-parallel

  publish_npm_packages:
    runs-on: ubuntu-latest
    if: github.repository == 'sqldelight/sqldelight'
    permissions:
      contents: read
      id-token: write
    needs: publish_archives

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      # https://github.com/gradle/gradle-build-action/issues/561
      - name: Create Gradle files
        run: |
          cd ~
          mkdir -p .gradle/ && touch .gradle/gradle.properties
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        id: setup-java
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.ci-java-version
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Gradle Java installations paths
        run: |
          cd ~/.gradle
          echo "org.gradle.java.installations.paths=${{ steps.setup-java.outputs.path }}" >> gradle.properties
      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-cleanup: always

      - name: Get Version
        run: cat gradle.properties | grep --color=never VERSION_NAME >> $GITHUB_OUTPUT
        id: version

      - name: Assemble NPM Packages
        run: ./gradlew :drivers:web-worker-driver:sqljs:assemblePackage

      - name: Publish SNAPSHOT Packages
        working-directory: drivers/web-worker-driver/sqljs/build/package
        if: ${{ success() && contains(steps.version.outputs.VERSION_NAME, 'SNAPSHOT') }}
        run: npm publish --tag snapshot

      - name: Publish Packages
        working-directory: drivers/web-worker-driver/sqljs/build/package
        if: ${{ success() && !contains(steps.version.outputs.VERSION_NAME , 'SNAPSHOT') }}
        run: npm publish

  publish_release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - publish_archives
      - publish_plugin
      - publish_npm_packages
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Extract release notes
        id: release_notes
        uses: ffurrer2/extract-release-notes@273da39a24fb7db106a35526c8162815faffd31d # v3.1.0

      - name: Create release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

env:
  GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.daemon=false -Dorg.gradle.vfs.watch=false -Dorg.gradle.logging.stacktrace=full
